---
title: "Lab 1 Clustering Group 10"
output:
  pdf_document:
    latex_engine: lualatex
date: "2025-02-03"
author:
  - Liuxi Mei
  - Xiaochen Liu
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## SimpleKmeans

Apply "SimpleKMeans" to your data. In Weka euclidian distance is
implemented in SimpleKmeans. You can set the number of clusters and seed
of a random algorithm for generating initial cluster centers. Experiment
with the algorithm as follows:

1)  Choose a set of attributes for clustering and give a motivation.
    (Hint: always ignore attribute "name". Why does the name attribute
    need to be ignored?)

The set is chosen is the attributes excluding attributes 'Names',
'Protein', and 'Fat'. The reason for excluding 'Protein' and 'Iron' data
is that they both have quite similar mean values across clusters, see
picture below , which means that the differences among cluster are
insignificant and contribute quite less to clustering results.

![Clustering result with all numeric
attributes](Pictures/1.png){width="500"}

'Name' is also ignored as it is a string attribute. For clustering,
Euclidean distance can not be calculated for strings and Weka will also
report a mistake.

2)  Experiment with at least two different numbers of clusters, e.g. 2
    and 5, but with the same seed value 10.

    ![Calculated results with 3 clusters, seed set to
    10](Pictures/2.png){width="500"}

    ![Calculated results with 5 clusters, seed set to
    10](Pictures/3.png){width="600"}

3)  Then try with a different seed value, i.e. different initial cluster
    centers. Compare the results with the previous results. Explain what
    the seed value controls.

    With seed = 20, following results are given. Both the numbers of
    instances in clusters and the instances belong to clusters have
    changed. As a result, the variance and mean value for each cluster
    are different from the previous results.

    When initializing this algorithm, N (corresponding to cluster
    number) initial 'means' are generated randomly within the data
    domain, which is controlled by the seed number. Different seeds give
    different initial 'means', resulting different results in this case.

    ![Calculated results with 3 clusters, seed set to
    20](Pictures/4.png){width="500"}

    ![Calculated results with 5 clusters, seed set to
    20](Pictures/5.png){width="600"}

4)  Do you think the clusters are "good" clusters? (Are all of its
    members "similar" to each other? Are members from different clusters
    dissimilar?)

Those are not 'good' clusters, at least not appropriate for the
application of SimpleKmeans method. If they are obviously similar to
each other, the clusters should include the same instances despite
different seed values.

By applying 'standardize' filter to raw data and with seed set to 20,
the regenerated results are shown as the figures below. When cluster
number is chosen to be 3, cluster 0 and 1 different calcium values but
very similar Energy and Fat values. And cluster 2 seems to be a more
independent. For 5 clusters, cluster 0 and 4 are similar in Energy and
Fat values but unsimilar calcium values. The similarity in calcium
values is also noticed between cluster 0 and 1.

![Calculated results with 3 clusters, seed set to 20, with standardized
data](Pictures/6.png){width="500"}

![Calculated results with 5 clusters, seed set to 20, with standardized
data](Pictures/7.png){width="600"}

5)  What does each cluster represent? Choose one of the results. Make up
    labels (words or phrases in English) which characterize each
    cluster.

Take figure 6 as an example, cluster 0 is the one with moderate energy,
moderate fat and high calcium level. Cluster 1 is the one with moderate
energy, moderate fat and low calcium level. Cluster 3 is the one with
high energy, high fat and moderate energy level.

## MakeDensityBasedClusters

Now with MakeDensityBasedClusters, SimpleKMeans is turned into a
density-based cluster. You can set the minimum standard deviation for
normal density calculation. Experiment with the algorithm as the
follows:

1)  Use the SimpleKMeans clusterer which gave the result you haven
    chosen in 5).

2)  Experiment with at least two different standard deviations. Compare
    the results. (Hint: Increasing the standard deviation to higher
    values will make the differences in different runs more obvious and
    thus it will be easier to conclude what the parameter does)

    With 0.001 and 0.5 selected for minStdDev, the same cluster
    centroids for 2 custers are initilized, see figure 8. However, the
    fitted cluster vary and cluster have 9 and 8 instances when the
    minStdDev is 0.001 and 0.5 respectively. The standard deviations for
    fitted normal distribution models are also different to fulfill the
    setting of minStdDev. As a result, log likelihood is -1.7 for the
    model with 0.001 minStdDev and 3.8 for the other.

    ![Initial clusters with cebtroids with MakeDensityBasedClusters
    applied](Pictures/8.png){width="600"}
